* Added validity check for the current zone file * Added timestamps in error messages * Print named-checkzone output if errors occured

diff --git a/tools/zone_update/zone_update b/tools/zone_update/zone_update
--- a/tools/zone_update/zone_update
+++ b/tools/zone_update/zone_update
@@ -1,5 +1,5 @@
 #!/bin/bash
-# zone_update bash script Version 0.7
+# zone_update bash script Version 0.8
 # Copyleft 2005 - Ernest0x (ernest0x at yahoo dot gr)
 
 # Discription
@@ -11,9 +11,9 @@
 
 # Notes
 # -----
-# - The php-generated zone file must include a line that contains a "; serial" substring. 
-#   This line gives its place to a new serial line, constructed by this script.
-# --------------------------------------------------------------------------------------- #
+# - Both your system's zone file and the php-generated zone file must include a 
+#   line that contains a "; serial" comment string. This line gives its place to 
+#   a new serial line, constructed by this script.
 
 
 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11
@@ -40,6 +40,15 @@ if [ ! -e $ZONES_ROOT$CUR_ZONE ]; then
    echo "file '$ZONES_ROOT$CUR_ZONE' does not exist"
    exit
 fi
+
+# Check the syntax of the current zone file and make sure it includes "; serial" line
+if ! ( named-checkzone -q $CUR_ZONE $ZONES_ROOT$CUR_ZONE && grep -q "; serial" $ZONES_ROOT$CUR_ZONE ) ; then
+   echo "`date` - $ZONES_ROOT$CUR_ZONE has errors (wrong syntax or  missing '; serial' comment)."
+   echo "#### START of named-checkzone output (if OK then '; serial' comment is missing) ####"
+   echo "`named-checkzone $CUR_ZONE $ZONES_ROOT$CUR_ZONE`"
+   echo "#### END of named-checkzone output ####"
+   exit
+fi
  
 # Where we will temporarily save the php-generated zone file.
 PHP_ZONE="/tmp/php-zone"
@@ -51,11 +60,19 @@ CUR_ZONE_S="/tmp/cur-zone-s"
 PHP_ZONE_S="/tmp/php-zone-s"
 
 # Make PHP_ZONE
+cd `dirname $PHP_SCRIPT`
 php $PHP_SCRIPT $CUR_ZONE > $PHP_ZONE
 
 # Extract the serial number of the current zone file.
 # Remember to change '2' to '3' on the next millenium change. :P
 CUR_SERIAL=`grep "; serial" $ZONES_ROOT$CUR_ZONE | grep -o "2........."`
+
+# Check the validity of CUR_SERIAL
+CUR_SERIAL_CHARS=`echo -n $CUR_SERIAL | wc -m`
+if [ $CUR_SERIAL_CHARS -ne 10 ] || ! date -d `echo $CUR_SERIAL | cut -c 1-8` > /dev/null 2>&1 ; then
+    echo "`date` - Serial line in $ZONES_ROOT$CUR_ZONE is not valid."
+    exit
+fi
 
 # Day Of CUR_SERIAL
 DCS=`echo $CUR_SERIAL | tail -c +7 | head -c 2`
@@ -117,7 +134,10 @@ else
   if named-checkzone -q $CUR_ZONE /tmp/$CUR_ZONE ; then
      mv -f /tmp/$CUR_ZONE $ZONES_ROOT
   else
-     echo "PHP-generated file has errors (possible database failure)"
+     echo "`date` - PHP-generated file has errors (possible database failure)"
+     echo "#### START of named-checkzone output ####"
+     echo "`named-checkzone $CUR_ZONE /tmp/$CUR_ZONE`"
+     echo "#### END of named-checkzone output ####"
      rm -f $PHP_ZONE $CUR_ZONE_S $PHP_ZONE_S /tmp/$CUR_ZONE
      exit
   fi
